# Generated by Django 2.2.4 on 2020-05-01 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='exam_app2.User'),
        ),
    ]
